[package]
name = "slicism-slice-echo"
version = "1.0.0"
authors = ["Félix Saparelli <felix@passcod.name>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.8"
serde_derive = "1.0.105"
serde = "1.0.105"
serde_cbor = "0.11.1"
