[package]
name = "slicism-slice-echo"
version = "1.0.0"
authors = ["Félix Saparelli <felix@passcod.name>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.8"
wee_alloc = "0.4.5"
num-traits = "0.2.11"
num-derive = "0.3.0"