bind = "0.0.0.0:8080"
display_errors = true

[gc]
interval = "30s"

[[map]]
src = "/net"
dst = "/net.wasm"

[[map]]
src = "/capture/(.+)(?:/(.+))?"
dst = "/echo.wasm"
post = { hello = "$1", world = "$2" }