bind = "0.0.0.0:8080"
preload = true
static_files = false

[[map]]
src = "/net"
dst = "/net.wasm"

[[map]]
src = "/capture/(.+)(?:/(.+))?"
dst = "/echo.wasm"
post = { hello = "$1", world = "$2" }

[cap.net]
enabled = true
only = [
	"/net.wasm"
]
