[package]
name = "slicism-edit"
version = "1.0.0"
authors = ["Félix Saparelli <felix@passcod.name>"]
edition = "2018"

[dependencies]
anyhow = "1.0.27"
async-std = "1.5.0"
clap = "2.33.0"
error-chain = "0.12.2"
hex = "0.4.2"
structopt = "0.3.12"
walrus = "0.15.0"
